apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: my-nginx
    type: front-end-2
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80