apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: nginx
    typeapp: frontend
  ports:
    - nodePort: 32450
      protocol: TCP
      port: 8080
      targetPort: 80