apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume-2
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /files/emptyfolder