apiVersion: v1
kind: PersistentVolumeClaim
metada:
  name: my-persistent-volume-claim-2
spec:
  #accessModes:
  #  - ReadWriteMany
  #volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
      accessModes:
      - ReadWriteMany
      storageClassName: ""