apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    typeapp: frontend
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      typeapp: frontend
  template:
    metadata:
      labels:
        app: nginx
        typeapp: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80

