apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    typeapp: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      typeapp: frontend
  template:
    metadata:
      labels:
        app: nginx
        typeapp: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-label
                operator: In
                values:
                - worker-2